server:
  port: 8001
  servlet:
    context-path: /app # 上下文件路径，请求前缀 ip:port/article

spring:
  application:
    name: wallet-server # 应用名
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog_article?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.zrrd.blog.entities
  # xxxMapper.xml 路径
  mapper-locations: classpath*:com/xxxx/wallet/mapper/xml/*.xml



